// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTYPVMMDx_ZGTFvrUwyAgMzGvtEA54Z_k',
    appId: '1:840568536135:web:648847167b06684e874562',
    messagingSenderId: '840568536135',
    projectId: 'cutbayan',
    authDomain: 'cutbayan.firebaseapp.com',
    storageBucket: 'cutbayan.firebasestorage.app',
    measurementId: 'G-PTG4C128L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_QbOMauQ-okfCEGO1brfOmQVY9T78rHA',
    appId: '1:840568536135:android:070d9c14a06e4889874562',
    messagingSenderId: '840568536135',
    projectId: 'cutbayan',
    storageBucket: 'cutbayan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqXbcQ_OPV7eAHD8Ekh0njJQgY8EHFfU',
    appId: '1:840568536135:ios:bbd0200ddb16dd38874562',
    messagingSenderId: '840568536135',
    projectId: 'cutbayan',
    storageBucket: 'cutbayan.firebasestorage.app',
    iosBundleId: 'com.example.sylo',
  );
}
